# Generated by Django 2.1.5 on 2020-03-24 01:33

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True),
        ),
    ]
