# Generated by Django 2.1.5 on 2020-03-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Content',
            new_name='Contents',
        ),
    ]
