# Generated by Django 2.1.5 on 2020-03-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名字')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(verbose_name='用户账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('phone', models.IntegerField(max_length=11, verbose_name='手机号')),
                ('name', models.CharField(max_length=20, verbose_name='用户名字')),
            ],
        ),
    ]
