# Generated by Django 2.1.5 on 2020-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='article_cover/2020/12/12', upload_to='article_cover/%Y/%m/%d', verbose_name='封面图片'),
        ),
    ]
